# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: reijulab
email: samuli.reijula@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
  Philosopher of science @ Uni Helsinki. cognitive_science; computational_social_science; institutional_epistemology; evidence_based_policy; models_and_simulations; conceptual_change
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.samulireijula.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: samulipo
github_username:  samulipo
author: Samuli Reijula

# CUSTOM PAGES IN HEADER
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - projects.md #sometimes takes a while to update
  - publications.md
  - presentations.md
  - teaching.md
  - log.md
  - wall.md
  - contact.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: G-HZL0D881P8

excerpt_separator: <!--more-->


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# for image gallery, 2023-09-15, see https://dmnfarrell.github.io/software/jekyll-galleries
imagesurl: "/assets/gallery/images/"
thumbsurl: "/assets/gallery/thumbnails/"